### ISSUE TITLE
Available jar for download

### ISSUE THREAD

**Issue by dobau** [rpatil26/webutilities#18]
Available the jar file for download of release 0.0.7

**Comment by rpatil26** [comment]
Please check release for 0.0.7 here https://github.com/rpatil26/webutilities/releases/tag/webutilities-0.0.7

It is recommended to use with maven to manage the decencies better. http://search.maven.org/#artifactdetails%7Ccom.googlecode.webutilities%7Cwebutilities%7C0.0.7%7Cjar
