### ISSUE TITLE
Enable YUIMinFilter processing for urls without extension

### ISSUE THREAD

**Issue by arpol1993** [rpatil26/webutilities#23]
YUIMinFilter checks whether to apply compression logic based on several aspects including check for obligatory URL extension (lowerUrl.endsWith(EXT_JS) || lowerUrl.endsWith(EXT_JSON) || lowerUrl.endsWith(EXT_CSS).
Could you please make url extension optional and decide whether to compress response based on it's content type.

**Comment by rpatil26** [comment]
Good idea. Since filter already has ability to target what to include/exclude through config, having this mandatory check in the code doesn't make sense.
