### ISSUE TITLE
[compression] headers do not get written under load

### ISSUE THREAD

**Issue by antalk** [rpatil26/webutilities#24]
Hi,

We are using your library (0.0.8) in an enterprise environment (jboss 5.2.0EAP) and have noticed that when using the gzip compression filter in some rare cases the (http)response is already closed and returned to the client before the compression headers ("Vary" and "Content-Encoding") have been written. Resulting in binary content (the zip) send to the client as plain text, giving garbage.

I was able to reproduce this by using chrome and use throttling on the requests, simulating a 2G connection and then pushing requests as fast as possible.

Also i was able to fix this by switching 2 lines of code in 'CompressedServletOutputStream' in the method 'private OutputStream getCompressed() throws IOException {' by FIRST setting the headers through the 'useCompression' method and only then creating the compressed stream.

if (compressed == null) {
        	//we are switching to compression here, write compression headers
            compressedResponseWrapper.useCompression();
            compressed = encodedStreamsFactory.getCompressedStream(uncompressedStream);
}

I must confess that im still not sure as to why the response in some cases gets closed before these headers are written, but this solves it for us.

Edit: it looks like the connections are closed on the client side (eg browser)

**Comment by rpatil26** [comment]
Thanks for describing the issue in details. I think it's tricky to get to the root cause. However, if writing headers first helps then it's not bad ideas. In fact, writing appropriate headers early should be fine. I would try to investigate more, but feel free to create PR if you'd like to.
