### ISSUE TITLE
Invalid encoding of javascript files when using CharacterEncodingFilter and ResponseCacheFilter together

### ISSUE THREAD

**Issue by bojanb123** [rpatil26/webutilities#28]
CharacterEncodingFilter filter is configured to set an utf-8 encoding for javascript files. In doFilter method chan.doFilter method is called before response encoding is actualy set. Chain.doFilter invokes ResponseCacheFilter which flushWriter before encoding is actually set (WebUtilitiesResponseWrapper.fill method calls flushWriter method)

**Comment by rpatil26** [comment]
Please do share the easy steps/configuration to repro this if you have it handy.

**Comment by bojanb123** [comment]
Hello,

Unfortunatelly i was unable to upload a demo application zip file to the blog. This is the reason i'm sending you this mail.

I created a demo application. An application has a few filters, two of them are problematic. ResponseCacheFilter is currently enabled but produces wrong character encoding. YUIMinFilter is commended out because of StringIndexOutOfBoundsException.

The content of a demo application is the output that produces DocToHelp application, which is used for generating help files from a word document. I removed some document files to reduce zip size.

Start an application and browse to the page http://localhost:8080/mavenproject2-1.0-SNAPSHOT/help/index.html
You will notice invalid character encoding.

Best regards,
Bojan

**Comment by rpatil26** [comment]
Thanks but I still do not have enough details to debug this at this time. Check if you can share the demoapp through drive/dropbox etc. that has these issues.

**Comment by bojanb123** [comment]
Hello,

I uploaded files to dropbox. Use following links to download:

https://www.dropbox.com/s/dsip22ej9kud8zh/mavenproject2.zip?dl=0
https://www.dropbox.com/s/uadsq0sz0a8ibdb/ProperEncodingWithoutTwoFilters.PNG?dl=0
https://www.dropbox.com/s/ql0xcyn6s476bek/InvalidEncodingWithAFilter.PNG?dl=0

Best regards,
Bojan

**Comment by lpcman** [comment]
@rpatil26  I debug source code in my local environment, finally find out add specific DEFAULT_CHARSET in JSCSSMergeServlet.java as following screen shot solve this bug.
![image](https://cloud.githubusercontent.com/assets/4230823/21353140/b176f862-c6ff-11e6-8673-855a18d6c3fa.png)

**Comment by rpatil26** [comment]
Thanks for the details. Would you like to sent PR?

**Comment by rpatil26** [comment]
Submitted. Thanks @lpcman for the help.
